Add validations - Part 2
MP-ES/k8s-deploy pull request #9
Opened 2021-07-23 18:17 UTC by estevao90

2021-07-26 20:08 UTC, izontm approved these changes

2021-07-26 21:01 UTC, eulercb requested changes

2021-07-27 15:53 UTC, estevao90 commented on src/entities/deployenv.go
> +			// validate ingresses
É... também não sou muito fã dessas docs pq gera mais um ponto de manutenção. rs

2021-07-27 16:16 UTC, eulercb approved these changes

2021-07-27 17:18 UTC, merged